### ISSUE TITLE
[Critical Error] - Getting logged out after clicking "Visit Website" + Error when clicking one of the website products

### ISSUE THREAD

**Issue by GeoCommander** [frappe/webshop#112]
**Description:**
Getting logged out after clicking website and clicking one of the products.

**System:**
ERPNext: v15.19.2
Frappe Framework: v15.20.0
Frappe HR: v15.16.0
Payments: v0.0.1 (v15-latest-April-09-2024)
Webshop: v0.0.1 (v15-latest-April-09-2024)

**Bug:**
![image](https://github.com/frappe/webshop/assets/71740113/c430ccb8-5eeb-4d1a-9cef-dc17cef6cdef)

**Traceback:**

Traceback (most recent call last):
File "apps/frappe/frappe/website/serve.py", line 20, in get_response
response = renderer_instance.render()
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/website/page_renderers/document_page.py", line 41, in render
html = self.get_html()
^^^^^^^^^^^^^^^
File "apps/frappe/frappe/website/utils.py", line 523, in cache_html_decorator
html = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/website/page_renderers/document_page.py", line 52, in get_html
return frappe.get_template(self.template_path).render(self.context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "env/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
self.environment.handle_exception()
File "env/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
raise rewrite_traceback_stack(source=source)
File "apps/webshop/webshop/templates/generators/item/item.html", line 2, in top-level template code
{% from "webshop/templates/includes/macros.html" import recommended_item_row %}
^^^^^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/templates/web.html", line 1, in top-level template code
{% extends base_template_path %}
^^^^^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/templates/base.html", line 69, in top-level template code
{% block content %}
File "apps/frappe/frappe/templates/web.html", line 72, in block 'content'
{{ main_content() }}
File "env/lib/python3.11/site-packages/jinja2/sandbox.py", line 393, in call
return __context.call(__obj, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "env/lib/python3.11/site-packages/jinja2/runtime.py", line 777, in _invoke
rv = self._func(*arguments)
^^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/templates/web.html", line 15, in template
{% block page_container %}
^^^^^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/templates/web.html", line 30, in block 'page_container'
{%- block page_content -%}{%- endblock -%}
^^^^^^^^^^^^^^^^^^^^^^^^^
File "apps/webshop/webshop/templates/generators/item/item.html", line 20, in block 'page_content'
{% include "templates/generators/item/item_details.html" %}
^^^^^^^^^^^^^^^^^^^^^^^^^
File "apps/webshop/webshop/templates/generators/item/item_details.html", line 38, in top-level template code
{% include "templates/generators/item/item_add_to_cart.html" %}
^^^^^^^^^^^^^^^^^^^^^^^^^
File "env/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
raise rewrite_traceback_stack(source=source)
File "apps/webshop/webshop/templates/generators/item/item_add_to_cart.html", line 181, in template
{% endif %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.

**Comment by hardik-limendo** [comment]
Hello, This issue has been fixed. Please refer #113

**Comment by GeoCommander** [comment]
> Hello, This issue has been fixed. Please refer #113

hi, I used latest version-15 yesterday but still faced same issue. I will try again

**Comment by GeoCommander** [comment]
I just checked. worked today. Fingers crossed next time
